stateDiagram-v2
.NETStandard,Version=v2.0 --> 🏗️Microsoft.ServiceProfiler.Orchestration/99.2022.507.1241_dev
🏗️Microsoft.ServiceProfiler.Orchestration/99.2022.507.1241_dev --> 🏗️Microsoft.ServiceProfiler.Logging/99.2022.507.1241_dev
🏗️Microsoft.ServiceProfiler.Logging/99.2022.507.1241_dev --> 📦Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/2.12.0
📦Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/2.12.0 --> 📦Newtonsoft.Json/10.0.3
🏗️Microsoft.ServiceProfiler.Orchestration/99.2022.507.1241_dev --> 🏗️Microsoft.ServiceProfiler.Contract/99.2022.507.1241_dev
🏗️Microsoft.ServiceProfiler.Contract/99.2022.507.1241_dev --> 📦Newtonsoft.Json/10.0.3
.NETStandard,Version=v2.0 --> 🏗️Microsoft.ServiceProfiler.Utilities/99.2022.507.1241_dev
🏗️Microsoft.ServiceProfiler.Utilities/99.2022.507.1241_dev --> 📦Newtonsoft.Json/10.0.3
