# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /

# Copy csproj and restore as distinct layers
COPY /ProjectAssets.Core/*.csproj ./ProjectAssets.Core/
COPY /ProjectAssets.CLI/*.csproj ./ProjectAssets.CLI/

RUN dotnet restore ProjectAssets.CLI

# Copy everything else and build
COPY ./ProjectAssets.Core ./ProjectAssets.Core
COPY ./ProjectAssets.CLI ./ProjectAssets.CLI
# Correct case
COPY ../Directory.Build.props ./Directory.Build.props 
RUN dotnet publish ProjectAssets.CLI -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "ast.dll"]