name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore src/ProjectAssets.CLI

    - name: Build
      run: dotnet build -c Release src/ProjectAssets.CLI --no-restore /p:Version=${VERSION}

    - name: Test
      run: dotnet test tests/ProjectAssets.Core.Tests --verbosity normal

    - name: Publish to linux x64
      run: dotnet publish -c Release src/ProjectAssets.CLI -r linux-x64 --self-contained -p:PublishSingleFile=true -o out/linux-x64 /p:Version=${VERSION}

    - name: Publish to win x64
      run: dotnet publish -c Release src/ProjectAssets.CLI -r win-x64 --self-contained -p:PublishSingleFile=true -o out/win-x64 /p:Version=${VERSION}

    - uses: actions/upload-artifact@v3
      name: Upload Linux Artifacts
      with:
        name: ast-cli.linux-x64.${{github.ref_name}}
        path: out/linux-x64
        retention-days: 1

    - uses: actions/upload-artifact@v3
      name: Upload Windows Artifacts
      with:
        name: ast-cli.win-x64.${{github.ref_name}}
        path: out/win-x64
        retention-days: 1